name: CI

on:
  push:
    branches: master

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.10
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Take photo of github.com
      uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
      with:
        url: https://github.com
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - run: ruby -v
    - name: Build and test with cucumber
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec cucumber features/capybara.feature
    - name: test
      if: failure() || success()
      run: bundle exec cucumber features/named_driver_feature.feature


  # job_2:
  #   name: Job 2
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: eregon/use-ruby-action@v1
  #     with:
  #       ruby-version: 2.6
  #   - run: ruby -v
  #   - name: Build and test with cucumber
  #     run: |
  #       gem install bundler
  #       bundle install --jobs 4 --retry 3
  #       bundle exec cucumber
