name: CI

on:
  push:
    branches: master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.10
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v1
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - run: ruby -v
    - name: Build and test with cucumber
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - name: testing
      if: failure() || success()
      run: bundle exec cucumber features/capybara.feature
    - name: test
      if: failure()
      run: bundle exec cucumber features/named_driver_feature.feature


  # job_2:
  #   name: Job 2
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: eregon/use-ruby-action@v1
  #     with:
  #       ruby-version: 2.6
  #   - run: ruby -v
  #   - name: Build and test with cucumber
  #     run: |
  #       gem install bundler
  #       bundle install --jobs 4 --retry 3
  #       bundle exec cucumber
