name: CI

on:
  push:
    branches: master

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.10
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /Desktop/test/testing/tmp/screenshots
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - run: ruby -v
    - name: Build and test with cucumber
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: testing
      run: bundle exec cucumber features/capybara.feature
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: my-artifact
        path: /Desktop/test/testing/tmp/screenshots
    - name: test
      if: failure() || success()
      run: bundle exec cucumber features/named_driver_feature.feature
