name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - run: ruby -v
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Start MongoDB
      uses: getong/mongo-action@v1.1
      with:
        mongo version: '4.2-bionic'
        host port: 27017
    - name: Build and test with cuucmber
      run: |
        gem install bundler
        bundle install
        bundle exec cucumber
