name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.10
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v2
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - run: ruby -v
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install mongodb tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb-org
    - name: Build and test with cucumber
      run: |
        gem install bundler
        bundle install
        bundle exec cucumber features/capybara.feature
        bundle exec cucumber features/named_driver_feature.feature
